### ISSUE TITLE
generating account send me to captcha even when using new ip and or vpn

### ISSUE THREAD

**Issue by maxPrakken** [b8ff/Sunset#1]
When i try to use Sunset i get send to the google captcha no matter what I try, I renew my IP, use a VPN, use a proxy. all get send straight to the captcha

**Comment by waxnet** [comment]
That is how its supposed to be, Sunset doesn't have a captcha solver so you have to complete it by yourself, but... If you get sent to the captcha and after completing it successfully you get send again to captcha or to the phone verification screen you need to change IP.
