### ISSUE TITLE
Implement CAPTCHA solver

### ISSUE THREAD

**Issue by John-Wick23** [b8ff/Sunset#7]
Please implement auto captcha solver using https://www.capsolver.com This site allows to solve Funcaptcha easily and will help a lot if it can be implemented in the bot.

**Comment by waxnet** [comment]
If I add any type of Captcha solver I would have to make the generator paid and obfuscated which is not what I want.

**Comment by John-Wick23** [comment]
> If I add any type of Captcha solver I would have to make the generator paid and obfuscated which is not what I want.

Why would you need to make it paid and obfuscated? You can add support for the captcha solvers and allow the users to purchase the CAPTCHA services if ever required.

**Comment by waxnet** [comment]
Why would I make a whole captcha solver system if I cannot test it nor use it. This project is something i'm doing for fun not for money, so I don't want to waste my money (to test captcha solver services) and time on something that can be easily completed manually in about 10 seconds which is also what a captcha solver would take to bypass it.
